# Generated by Django 4.0.3 on 2022-04-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consults', '0004_consult_age_consult_email_consult_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='email',
        ),
    ]
