# Generated by Django 4.0.3 on 2022-05-01 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consults', '0005_remove_consult_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
