# Generated by Django 4.0.3 on 2022-03-06 09:58

from django.db import migrations, models
import enum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=150)),
                ('views', models.IntegerField(verbose_name=enum.auto)),
                ('Date', models.DateField()),
            ],
        ),
    ]
