# Generated by Django 4.0.3 on 2022-03-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0002_alter_artical_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='text',
            field=models.TextField(),
        ),
    ]
