# Generated by Django 4.0.3 on 2022-03-06 13:01

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0003_alter_artical_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='img',
            field=models.FileField(default='SOME STRING', upload_to=pathlib.PureWindowsPath('C:/Users/zakaa/Desktop/project/mysite/photo')),
        ),
    ]
