# Generated by Django 4.0.3 on 2022-03-06 13:03

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0004_artical_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='img',
            field=models.FileField(default='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAeFBMVEUAAAD///9aWlrm5uZDQ0MICAjy8vIkJCSXl5f7+/unp6eTk5NxcXE8PDxAQEDb29vz8/O4uLjs7OwpKSmysrLAwMDg4ODPz89nZ2fIyMiEhISNjY2kpKR7e3sPDw9jY2NSUlIzMzMXFxcgICCHh4dJSUk2NjZUVFRFQqk1AAAEfklEQVR4nO2aa3eiOhRAiThWkKlAUeuDamud/v9/eK0VchICU2k6XYu797eGw4GdkKcNAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPg/8nL/u8Jn2ied9pfPvD0YqYrJk8e0pzpt9OAxbR+0Yeizsse64u48pu0Dhj35R4ZTZZOvisSMGZrhhVj2/UEaqvRRxwzTUCmtOFRDPUkN1VBlVcxgDSdVIw7FMGooVj1xKIaq2Cev2UQYTq8xgzHc2gXra8xgDGcfJevBG74O3jCpC6rpotXw6XEzm87Kw2cedCrPoZu9KPkxw63VMVsNH1fV8DuJzzvjTVxx0dhVfxXvk840v8ZGi/tOwzIWFM/fYjivCw5dhqelkmxE/72MwfrSOBjJEboeol2GMyupX8NLk/1Z1H/PqxiX4auy2OkbL1Wlp9fnxJps41ZDY/0RicW/H8P1dLqYi1epd4kOQ8dSKG0zTBqhjy2GO1kT6ciLYMeqLa5jmoYbxwpIYxk2Q3O34U7GpL7O9VoMo7q3uAxP7ptaDB2ULsNY1kXubXhta8PtS4dh+FXDtcOwkAHzp8DX1Nv+lc631eGobVh2CzoMl/G0kGPvpGmYyRZceVxZdOyeVHj4qEjbUL5rtCj3+yRL5fvZhtHlozx3Xl1ybxtm4qJa+PPrNlTRKXAYvomI5XX+Pq5EoW1YXp8V66K9aRgsxO2q8CnYuT+sTvEtQ1EpuU4kFC3DZRXyoEMS01DWj9p5FZSvu3pfKGXzVD4tdhiK1xFT1m+tZBnqUTlvMTQqd+ZXsLk/DI6lcMwdhnokDWUmvWqzZ/w6ZGmUaUNNVH/S32FYV95BPHLUMPylWyKTmbZmIm14qkP0krfN8LwU9f1Lm8tQDmyvDcMXbWj0mNJMpA3rzcRnDP1vpJyGYlldNAyfcuNizcZM1NNQTXzsmP5qKGauRcNQjBdrmSk2E/U1VLnXH5pbDMXEtW4a6vdUMlNoJrrFcCJSuhTHxTIM14ld/AVDMZhmTUPhLz7TmZXoFsP8xZgQc+tH7yr1OuhDc7YIErkjnzUNE+vyhdIuvKkNj8E8khsLQ1EP0qsvGhZJkmymmblx2DcNZROr1eh4Hl5PxqrrdsM749s/K4rh5lmUb4Pb6VyXumd8c6eq0uUyN2/qZXg0zn3CP/VNsSz2b7hzGXbv/XoaBg/GxxPWH6qxk+kxznYbfqysG4Z/2SD2MwzujBO5vNqCG+vkg2/DsdtQLnr8GQYPE+UYboym1bm8GE6uNeY4a1s1gqPWs7ZPGwZjoxXDj+FGnm547odZtUR0nZeuzdhIFa3npZ83DA7GJ/mheC8eIo7HvmyYx7pTO8+8rRuz9t3TDYbBmzGIhcf3Mj1012fUXzOM8lU2HcsY9+8W4nRc5Ulgn+rfYpjqGV4ekVR9sZov5j7/b/BzlMU8TSer3ds3P2e0TqNo+frNT/lhjj/9AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABO/gOOkTlPXUfXhgAAAABJRU5ErkJggg==', upload_to=pathlib.PureWindowsPath('C:/Users/zakaa/Desktop/project/mysite/photo')),
        ),
    ]
