# Generated by Django 4.0.3 on 2022-03-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0006_artical_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical',
            name='slug',
        ),
    ]
