# Generated by Django 4.0.3 on 2022-03-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0010_alter_artical_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical',
            name='img',
        ),
    ]
