# Generated by Django 4.0.3 on 2022-03-08 14:53

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0011_remove_artical_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='img',
            field=models.FileField(default='', upload_to=pathlib.PureWindowsPath('C:/Users/zakaa/Desktop/project/mysite/photo')),
        ),
    ]
