# Generated by Django 4.0.3 on 2022-03-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0012_artical_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical',
            name='img',
        ),
    ]
