# Generated by Django 4.0.3 on 2022-03-09 10:25

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0013_remove_artical_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='img',
            field=models.FileField(default='', upload_to=pathlib.PureWindowsPath('G:/project/mysite/photo')),
        ),
    ]
