# Generated by Django 4.0.3 on 2022-03-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0014_artical_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
