# Generated by Django 4.0.3 on 2022-03-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0018_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='category',
            field=models.CharField(default='coding', max_length=255),
        ),
    ]
