# Generated by Django 4.0.3 on 2022-03-29 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articals', '0021_alter_artical_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='Likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
