# Generated by Django 4.0.3 on 2022-04-28 06:58

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0022_artical_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='artical',
            name='img',
            field=models.FileField(default='', upload_to=pathlib.PureWindowsPath('C:/Users/ASUS/Desktop/project/project/mysite/photo')),
        ),
    ]
