# Generated by Django 4.0.3 on 2022-05-01 10:08

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0023_alter_artical_date_alter_artical_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='img',
            field=models.FileField(default='', upload_to=pathlib.PureWindowsPath('G:/project/mysite/photo')),
        ),
    ]
